#-------------------------------
# General Site Settings

menu:
- {name: 'Pages', url: 'pages/posts'}
- {name: 'About', url: 'pages/about'}
- {name: 'Contact', url: 'pages/contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Class website for Purchase College CS1, Fall 2020'
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: ''

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'namegoeshere'

#-------------------------------
# About Section

about: >
  # CS1

  This is the class website for CS1, fall 2020 at Purchase College, taught by Lee Tusman.

  You can find our course Moodle page [here](https://moodle.purchase.edu/moodle2/login/index.php). Our class Discord server is linked from Moodle as well.

  Our Learning Assistant is Sofia Jaramillo.

  Our class meets on Zoom Mondays 2:30pm

contact: >
  # Contact

  You may contact Lee through [email](mailto:lee.tusman@purchase.edu) if you have any questions or would like to bring up any issues.

#-------------------------------
# Work Section

projects:
# To list project pages, uncomment the following lines and add these files!
#- {name: 'Project One', folder: 'proj-1', file: 'projects/proj-1.html'}
#- {name: 'Project Two', folder: 'proj-2', file: 'projects/proj-2.html'}
#- {name: 'Project Three', folder: 'proj-3', file: 'projects/proj-3.html'}

#-------------------------------
# Contact Section

social:
#- {icon: 'twitter', link: '#'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
